# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_category_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modfield_time',
            new_name='modified_time',
        ),
    ]
